### ISSUE TITLE
Cannot destructure property 'urls' of '(intermediate value)' 

### ISSUE THREAD

**Issue by JoeApo108** [pokt-foundation/node-nanny#136]
**Describe the bug**
A NEAR mainnet stuck in pending state

LOG display: 
`nn_backend     | [MONITOR ERROR] Node: near-mainnet/NEAR/01 TypeError: Cannot destructure property 'urls' of '(intermediate value)' as it is null.     at Service.getOracles (/usr/src/node-nanny-backend/packages/core/src/services/health/service.ts:310:13)`

**To Reproduce**
1. Set host FQDN as **rpc.mainnet.near.org**
2. LoadBalander set off
3. In the Nodes section  HTTPS on, PORT: 443 (https://rpc.mainnet.near.org:443)
5. Automation set off

**Desktop:**
 - OS: Debian
 - Version PVE 5.15.35-3

**Comment by commoddity** [comment]
Hey @JoeApo108, could I get the Docker image tag of the version you are using? I believe this issue has been fixed in the latest beta build, which is tagged as `latest-beta` or `1.0.0-beta.11`. 

If you update the docker-compose.yml file tags for the node-nanny images to `pocketfoundation/node-nanny:latest-beta` and `pocketfoundation/node-nanny-ui:latest-beta`, respectively and then run `docker-compose pull && docker-compose up -d --force-recreate` to update to the latest images, I believe this should be cleared up.

Please let me know if that works for you or if the issue persists after updating.

I've also updated the example docker-compose.yml file on the `beta` branch (which is currently the default branch) to reflect the `latest-beta` tag.

**Comment by JoeApo108** [comment]
I do confirm that issue was fixed with `latest-beta` version.

My use case was just playing with all the possibilities NN offers and hit on such an error.

**Comment by commoddity** [comment]
Thanks for the clarification. Marking this as closed now.
